version: '3'

services:
  be:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGO_HOST: mongo
      MONGO_DB: cache-api-db
      MONGO_TEST_DB: cache-api-test-db
      MONGO_PORT: 27017
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run start:dev
    networks:
      - app-network
  mongo:
    image: mongo:4
    restart: always
    ports:
      - "27017:27017"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - app-network

networks:
  app-network:

volumes:
  node_modules:
